#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f *.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace combined.sv --exe combined_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vcombined.mk Vcombined

# run executable simulation file
echo "\nRunning simulation"
obj_dir/Vcombined
echo "\nSimulation completed"

